### PR TITLE
Gradcorrect

### PR DESCRIPTION
**Pull request by pvandyken**
Here's my first attempt at incorporating gradcorrect. I tried to combine what I found in `prepdwi` with some of the comments found at the bottom of the `prepdwi.smk` file.

I admit I still find the process as implemented in `prepdwi` confusing, so I'm not sure I fully did this correctly. In particular, I'm confused about:

- What image to use in calculating the gradcorrect warp file. Here I just used the avg b0 image, although in prepdwi the S0 from `dtifit` was used
- How exactly this relates to the b0->T1 transform. I'm calculating both the b0->T1 and the gradcorrection on the same untransformed source images, and then applying them sequentially. I'm concerned that this is not actually accurate, since the order of matrix multiplication matters.
- Prepdwi uses `convertwarp` to concatenate the gradcorrect and b0->T1 transforms. In fact, it uses the tool twice, the first time to convert the gradcorrect warp to relative, then the concatenation. In a comment at the bottom of `prepdwi.smk`, it was suggested to use `wb_command -convert-warpfield` followed by `antsApplyTransforms`. I tried to use these, but I think I have some mistakes:
  - I wasn't sure what the "from" format for `-convert_warpfield` was, so I used `-from-world`
  - For `antsApplyTransforms`, I listed both the b0-T1w transforms and the warp file under the same command. I'm not sure if that will properly concatenate them, or if I got the order correct.

I've attached the resulting DAG for visualization of what I've done. If you could review and let me know what changes are needed, that would be great.

gradcorrect

### CODE REVIEW

**Comment by akhanf** [comment]
Had a look just now and at least got things running on downsampled data, but running on some actual 7T data now to verify things are working.. I didn't want to clobber your branch, so have my commits on my gradcorrect branch.

To integrate things ultimately will want this part of the workflow to be optional, so once we sort out the remaining issues (e.g. registration, concatenation), will need to then add the appropriate conditionals on inputs to make it optional.

**Comment by pvandyken** [comment]
Thanks so much for getting the small bug fixes, I had meant to just verify the general structure is appropriate. Let me know how the 7T data goes

**Comment by akhanf** [comment]
No worries just had to do those in order to try it out

**Comment by pvandyken** [comment]
Thanks so much!

**Comment by akhanf** [comment]
@pvandyken ok for me to merge this in? seemed to run fine when I tested it out myself too. We can always make tweaks in future PRs in any case..

**Comment by pvandyken** [comment]
Yep, seemed to work on my end

**Pull request merged**
