### PR TITLE
Snakedwi code refactor + method selection flag

### PR DESCRIPTION
**Pull request by kaitj**
What started as just adding in a method selection flag and removing out of date flags ended up being refactor of the codebase with a lot more changes than I had originally intended (hope you don't mind!). I've also added in poetry tasks to test run through the different methods currently implemented with the test_data. Summarizing the major changes:

### Workflow related
* Restructured the .smk files and scripts to reduce the length of existing files
  * Moved diffusion, anatomical, metadata, and qc related files to their own respective sub-directories where it made sense
  * Split the SDC rules to their own files under an sdc sub-directory
* Updated python scripts
* Ran `quality_fix` poetry task for quality formatting updates
* Cleaned up CLI and added in `--sdc_method <method> [choices: topup (default), sdcflows, synthsr, none]` flag to choose between the different sdc processing methods
  * Removed out of date flags like `--use_<method>_sdc>`, where there were multiple different ones. Wasn't sure if they were conflicting or if you had to call multiple here to disable one and enable others.

### Non-workflow related
* Updated version indicated in the pyproject.toml and pipeline_description.json files
* Removed jupyter notebooks and the legacy prepdwi shell scripts (used during the initial dev?)
* Refactored actions: 
  * To add additional linters (black, flake8, etc.) 
  * Perform individual (non-dryrun) tests for each methods

I've tested the different methods on the test_data and they seem to work as intended, however haven't had a chance to test against real data. There are also a couple more items on the to-do list, but those were mostly adding in new features that I'll leave to a separate PR.

### CODE REVIEW

**Comment by akhanf** [comment]
Awesome, thanks! Was in need of a refactoring!

I'll go through it sometime this week or weekend. The one thing I noticed on a quick look is we can add another sdc choice called maybe 'optimal' where we pick the best one for each subject based on the available data (that is what it was doing).

Ali

**Comment by kaitj** [comment]
> The one thing I noticed on a quick look is we can add another sdc choice called maybe 'optimal' where we pick the best one for each subject based on the available data (that is what it was doing).

Ahh, I broke this functionality when I removed some of those flags (looking at the original code). Think I have a commit ready to go that should re-implement the functionality, but wanted to double check to make sure I understood how the original "optimal" was performed. 

The flags `--use_synthsr_sdc` was set to True and `--no_topup` was set to false by default and it would set the workflowopts by using one of those two options depending on the number of PE?

**Comment by akhanf** [comment]
Ah OK no worries we can reimplement with the refactored workflow and cli. Maybe the better way to set this up would be have a list to prioritize the different methods, and would pick the first one it is able to do for each subject.

 Or better yet, we could use the '+' argparse type for the --sdc_method, and it would act as the prioritized list. E.g. "--sdc_method topup synthsr " would use topup, if that isn't possible would use synthsr. That keeps the CLI simple but flexible enough for any use case, what do you think?

Best,
Ali
________________________________

**Comment by akhanf** [comment]
yeah you're right it is only used to specify what the method to use when pe_dirs <2 -- which could be one of synthsr, none, sdcflows, or the new one.. I wasn't specifically thinking about having it check for failures then move on, that would get complicated..  

So I guess the main use cases are:
1. the user only wants a particular sdc method (fail if not possible)
2. the user wants a particular sdc method (topup), and if that method is not possible, a back-up method to use (user's choice)

So we could hardcode the back-up method, or have some CLI way to set it, maybe --sdc-method-alternate?

**Comment by akhanf** [comment]
this all looks good to me! thanks for the major cleanup!!
Feel free to merge this in..

**Comment by kaitj** [comment]
Sounds good - I don't have write access to this repo, so unable to hit the merge button.

**Pull request merged**
